### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by mboldin** [ucfopen/canvasapi#135]
Uploading a file by name (string) seems to work (I see the file in Course Files) but an error is seen

Code:
    c = course.upload( file= fn )

Traceback (most recent call last):
  File "/home/ ...  Mycanvas1.py", line 149, in <module>
    c = course.upload( file= fn )
  File "/usr/local/lib/python3.5/dist-packages/canvasapi/course.py", line 245, in upload
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/canvasapi/upload.py", line 47, in start
    return self.request_upload_token(file)
  File "/usr/local/lib/python3.5/dist-packages/canvasapi/upload.py", line 69, in request_upload_token
    return self.upload(response, file)
  File "/usr/local/lib/python3.5/dist-packages/canvasapi/upload.py", line 96, in upload
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>>>

**Comment by mboldin** [comment]
Sorry  I see now this is the same issue as  "JSONDecodeError when uploading a file #129" and fixed in Development

**Comment by jessemcbride** [comment]
No worries, @mboldin. Let us know if anything else comes up.

**Comment by mboldin** [comment]
Nice code.  I am new to Canvas but actually teach Python.  You API as
helped me figure out how Canvas differs from Blackboard. I am working on
steps to convert Blackboard content to Canvas pages.  Do you have any
tricks or helper methods to upload pages ?


On Jan 14, 2018 4:30 PM, "Jesse McBride" <notifications@github.com> wrote:

No worries, @mboldin <https://github.com/mboldin>. Let us know if anything
else comes up.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ucfopen/canvasapi/issues/135#issuecomment-357544129>,
or mute the thread
