### ISSUE TITLE
Can't install on Mac OS X High Sierra: could not find a version that satisfies...

### ISSUE THREAD

**Issue by purpleHey** [ucfopen/canvasapi#173]
I'm on Mac OS X High Sierra 10.13.4, and Python version 2.7.14 and pip install canvasapi gives me:

edb-A11737-osx:CanvasReportUtils wwm394$ pip install canvasapi
Collecting canvasapi
  Could not find a version that satisfies the requirement canvasapi (from versions: )
No matching distribution found for canvasapi

Can you give me any pointers/ideas on what to try?

**Comment by jessemcbride** [comment]
That's strange.

What's the output of `pip install canvasapi -vvv`?

**Comment by purpleHey** [comment]
edb-A11737-osx:CanvasReportUtils wwm394$ pip install canvasapi -vvv
Collecting canvasapi
  1 location(s) to search for versions of canvasapi:
  * https://pypi.python.org/simple/canvasapi/
  Getting page https://pypi.python.org/simple/canvasapi/
  Looking up "https://pypi.python.org/simple/canvasapi/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  Could not fetch URL https://pypi.python.org/simple/canvasapi/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661) - skipping
  Could not find a version that satisfies the requirement canvasapi (from versions: )
Cleaning up...
No matching distribution found for canvasapi
Exception information:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for canvasapi
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/utils/outdated.py", line 126, in pip_version_check
    headers={"Accept": "application/json"},
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)

**Comment by jessemcbride** [comment]
It looks like this is an OpenSSL issue. Specifically, the version of Python that OS X ships with might 
contain an unsupported version of OpenSSL.

You're going to need to tinker with it, but I've found some discussions that might contain a fix for you. I'd recommend starting with the top one first and working your way down:

https://github.com/pypa/python-packaging-user-guide/issues/423
http://pyfound.blogspot.in/2017/01/time-to-upgrade-your-python-tls-v12.html
https://stackoverflow.com/questions/16370583/pip-issue-installing-almost-any-library
https://github.com/ansible/ansible/issues/33417

I'm going to close this as it isn't an issue with the library, but if you'd like some help troubleshooting, feel free to pop in our [Slack channel](https://ucf-open-slackin.herokuapp.com/) in #canvasapi and I'd be happy to help out.
