### ISSUE TITLE
Spaces in the API_KEY throw ValueError Exception

### ISSUE THREAD

**Issue by Thetwam** [ucfopen/canvasapi#301]
# Describe the bug

When the `API_KEY` passed to `Canvas` has a space character in the value, a `ValueError: too many values to unpack (expected 2)` exception is thrown.

# To Reproduce

1. Setup `API_URL` and `API_KEY` as normal.
2. Add an additional space character anywhere in the `API_KEY`
3. Setup Canvas object: `canvas = Canvas(API_URL, API_KEY)`
4. Make a call, e.g. `course = canvas.get_course(1)`

# Expected behavior

The whitespace should be automatically removed, or a more useful exception should be thrown.

# Environment information

- Python version (`python --version`)
3.7+
- CanvasAPI version (`pip show canvasapi`)
v0.14.0

# Additional context

```
Traceback (most recent call last):
  File "_test.py", line 42, in <module>
    course = canvas.get_course(COURSE_ID)
  File "<YANKED>canvasapi/canvas.py", line 603, in get_course
    "GET", uri_str.format(course_id), _kwargs=combine_kwargs(**kwargs)
  File "<YANKED>canvasapi/requester.py", line 191, in request
    "Headers: {headers}".format(headers=pformat(clean_headers(headers)))
  File "<YANKED>canvasapi/util.py", line 248, in clean_headers
    _, token = authorization_header.split(" ")
ValueError: too many values to unpack (expected 2)
```

**Comment by Thetwam** [comment]
@jessemcbride Thoughts on this one?

My gut says we should call `strip()` on incoming access tokens, similar to our manipulation of institution urls in `Canvas.__init__()`. Then, do a check if there are spaces remaining in the key. If there are, raise an exception stating so.

The above assumes that there are no valid canvas access tokens with spaces in them. Is that an assumption we want to make? If not, we'll need to modify `clean_headers` in `util.py` to handle tokens with spaces more gracefully.
